#!/bin/bash

## end setup on fail
set -e

echo "Installing Homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

if [[ "$(uname -m)" == "arm64" ]]; then
    echo "Arm64 detected, adding homebrew to path"
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/joshalletto/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

clear

echo "Installing awscli, nodejs, python, cask"
brew install --force awscli nodejs python cask
brew upgrade --force awscli nodejs python cask

echo "Installing yarn"
sudo npm i -g yarn

echo "Install mysqlworkbench, firefox, chrome, sublime text, spotify, cyberduck, vscode, docker"
brew install --cask --force mysqlworkbench firefox google-chrome sublime-text spotify slack postman cyberduck visual-studio-code docker
brew upgrade --cask --force mysqlworkbench firefox google-chrome sublime-text spotify slack postman cyberduck visual-studio-code docker
clear

brew doctor

echo "Installing Oh My ZSH"
curl -L http://install.ohmyz.sh | sh
clear

echo "Install complete!"
